### ISSUE TITLE
Not showing USD-M futures order

### ISSUE THREAD

**Issue by lamboforcats** [louismerlin/binance-bot#4]
Hi! Thanks for sharing. I have set up proper and was able to get my orders from Spot working. However, for Futures (USD-M), it is not working. Is there a config that I need to set up? Thanks!

**Comment by louismerlin** [comment]
Here is a way to make it work:

1. Try uncommenting line `49` of index.js, and then when you trigger a future, see what message the bot sends you
2. See the value of "eventType" from that message, and add it to the check on line `40`

I would be interested to know the "eventType" in question, I might add it to the bot if it works on your end :smile:

**Comment by lamboforcats** [comment]
Hi there. Tried your method but it doesn't work. As I look through the documentation I realise it could be due to difference in end point and the WebSocket URLs. After updated the URLS though, I keep getting an error: { code: -2014, msg: 'API-key format invalid.' }

**Comment by lamboforcats** [comment]
Hi there. Tried your method but it doesn't work. As I look through the documentation I realise it could be due to difference in end point and the WebSocket URLs.

**Comment by louismerlin** [comment]
That's probably it ! If you want to add this to the project, don't hesitate to submit a pull request :smile:
